-   id: clangd-tidy
    name: clangd-tidy
    description: This hook runs clangd-tidy for C++ linting
    entry: clangd-tidy
    language: python
    types: ["c", "c++", "file", "non-executable", "text"]
    args:
      - "-j8"
      - "--fail-on-severity error"
